# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Profiles',
                'doc_host': 'https://civildot.github.io',
                'git_url': 'https://github.com/civildot/Profiles',
                'lib_path': 'Profiles'},
  'syms': {'Profiles.core': {'Profiles.core.foo': ('core.html#foo', 'Profiles/core.py')}}}
