# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Profiles',
                'doc_host': 'https://civildot.github.io',
                'git_url': 'https://github.com/civildot/Profiles',
                'lib_path': 'Profiles'},
  'syms': { 'Profiles.profiles': { 'Profiles.profiles.profile': ('profiles.html#profile', 'Profiles/profiles.py'),
                                   'Profiles.profiles.submodel_gis': ('profiles.html#submodel_gis', 'Profiles/profiles.py')}}}